### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by girlsfamily** [ppya0812/scroll-vue-component#1]
render (h) {
     const shadowSvgEle = this.moreShadow &&
       <svg
         class='scroll-shadow'
         xmlns='http://www.w3.org/2000/svg'>
  请问这个是什么语法 webpack无法加载啊

**Comment by ppya0812** [comment]
render (h) 是jsx的语法，编译需要进行配置。
 babelrc： 需要配置加载器 "plugins": ["transform-vue-jsx"]
安装模块： babel-plugin-transform-vue-jsx   和 babel-plugin-syntax-jsx
